# Generated by Django 5.0.6 on 2024-10-27 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_custom_user_model_profile_pic_adminprofilemodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user_model',
            name='user_type',
            field=models.CharField(choices=[('seeker', 'Seeker'), ('recruiter', 'Recruiter')], max_length=10, null=True),
        ),
    ]
