# Generated by Django 5.0.6 on 2024-10-27 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_jobmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='Job_Image',
            field=models.ImageField(null=True, upload_to='Media/job_img'),
        ),
    ]
