# Generated by Django 5.0.6 on 2024-10-27 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0007_jobapplymodel_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplymodel',
            name='Skill',
            field=models.CharField(choices=[('python', 'PYTHON'), ('java', 'JAVA'), ('graphic', 'GRAPHIC'), ('marketing', 'MERKETING')], max_length=200, null=True),
        ),
    ]
