# Generated by Django 5.0.6 on 2024-10-27 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0008_alter_jobapplymodel_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplymodel',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobmodel', to='MyApp.jobmodel'),
        ),
    ]
