# Generated by Django 5.0.6 on 2024-10-27 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0009_alter_jobapplymodel_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplymodel',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MyApp.jobmodel'),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobmodel', to=settings.AUTH_USER_MODEL),
        ),
    ]
