# Generated by Django 5.0.6 on 2024-10-27 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0010_alter_jobapplymodel_job_alter_jobmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewerprofilemodel',
            name='Skill',
            field=models.CharField(choices=[('python', 'PYTHON'), ('java', 'JAVA'), ('graphic', 'GRAPHIC'), ('marketing', 'MERKETING')], max_length=100, null=True),
        ),
    ]
