# Generated by Django 5.0.6 on 2024-10-27 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0011_viewerprofilemodel_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewerprofilemodel',
            name='Skill',
        ),
        migrations.AddField(
            model_name='custom_user_model',
            name='Skill',
            field=models.CharField(choices=[('python', 'PYTHON'), ('java', 'JAVA'), ('graphic', 'GRAPHIC'), ('marketing', 'MERKETING')], max_length=100, null=True),
        ),
    ]
